### ISSUE TITLE
Tanya

### ISSUE THREAD

**Issue by bagussatoto** [nusabot-iot/dashboard-arduino#10]
Apakah ini produknya seperti mikrocontroller kah mas?
kalau dijalankan melalui apa ya?

**Comment by lorenzadam** [comment]
Ini library untuk Arduino IDE.

Menjadikan perangkat microcontroller seperti Arduino, ESP8266, ESP32, perangkat GSM, dan perangkat dengan ethernet dapat dihubungkan ke platform Dashboard menggunakan Arduino IDE.

Untuk informasi mengenai platform Dashboard bisa buka di website https://dashboard.nusabot.com

**Comment by bagussatoto** [comment]
Terimakasih Jawabannya

**Comment by lorenzadam** [comment]
Sama-sama 😁
Besok ada event pelatihan gratis kalau mau ikut. Mengenai penggunaan Dashboard.

Info lebih lanjut bisa di grup telegram Nusabot https://t.me/NusabotDiskusi
